// This file has been automatically generated by the Unreal Header Implementation tool

#include "FactoryGameModule.h"

IMPLEMENT_PRIMARY_GAME_MODULE(FFactoryGameModule, FactoryGameModule, "FactoryGameModule");

void FFactoryGameModule::StartupModule(){ }
void FFactoryGameModule::ShutdownModule(){ }
